# Namespace where the application will be deployed
namespace: "prod"

# Prefix for the repository where Helm charts are hosted
repository_prefix: "ardhmd"

alb:
  # Tags to associate with the Application Load Balancer
  tags: "Name=alb-petclinic-prod"

ingress:
  # Subnets for the ingress controller
  subnets: "subnet-040b0deb1d0b615db,subnet-0a697e68b5be14b84"
  # ACM certificate ARN for HTTPS
  certificateArn: "arn:aws:acm:eu-west-3:414147595918:certificate/f56d0bc0-9093-495a-a813-8526e8323556"
  # Hostname for the ingress controller
  host: "www-prod.vetops.net"
